Fix image update task and deployment image

diff --git a/tekton/update-image-version-task.yaml b/tekton/update-image-version-task.yaml
--- a/tekton/update-image-version-task.yaml
+++ b/tekton/update-image-version-task.yaml
@@ -7,50 +7,72 @@ metadata:
 
 spec:
 
-  params:
-
-    - name: image
-      type: string
-
-    - name: image-version
-      type: string
-
-
   workspaces:
-
-    - name: shared-workspace
-
+    - name: source
 
   steps:
 
     - name: update-image
 
-      image: alpine:3.19
+      image: maven:3.9.11-eclipse-temurin-21
 
-      workingDir: $(workspaces.shared-workspace.path)
+      workingDir: $(workspaces.source.path)
 
       script: |
         #!/bin/sh
-
         set -e
 
-
-        echo "Aggiorno immagine"
-
-        IMAGE="$(params.image):$(params.image-version)"
-
-        echo "Nuova immagine: $IMAGE"
+        echo "================================="
+        echo "Aggiornamento immagine Kubernetes"
+        echo "================================="
 
 
-        if [ ! -f k8s/deployment.yaml ]; then
-          echo "ERRORE: k8s/deployment.yaml non trovato"
+        chmod +x ./mvnw
+
+
+        IMAGE=$(./mvnw help:evaluate \
+          -Dexpression=docker.image \
+          -q \
+          -DforceStdout 2>/dev/null | grep -E '^[a-zA-Z0-9._/-]+$' | tail -1)
+
+
+        VERSION=$(./mvnw help:evaluate \
+          -Dexpression=project.version \
+          -q \
+          -DforceStdout 2>/dev/null | grep -E '^[0-9]+\.[0-9]+\.[0-9]+.*' | tail -1)
+
+
+        if [ -z "$IMAGE" ]; then
+          echo "ERRORE: immagine Docker non trovata"
           exit 1
         fi
 
 
-        sed -i "s|image:.*|image: $IMAGE|g" k8s/deployment.yaml
+        if [ -z "$VERSION" ]; then
+          echo "ERRORE: versione Maven non trovata"
+          exit 1
+        fi
 
 
-        echo "Nuovo deployment.yaml"
+        FULL_IMAGE="${IMAGE}:${VERSION}"
+
+
+        echo "Immagine finale:"
+        echo "$FULL_IMAGE"
+
+
+        if [ ! -f k8s/deployment.yaml ]; then
+          echo "ERRORE deployment.yaml non trovato"
+          exit 1
+        fi
+
+
+        sed -i "s|image:.*|image: ${FULL_IMAGE}|g" k8s/deployment.yaml
+
+
+        echo "================================="
+        echo "deployment.yaml aggiornato"
+        echo "================================="
+
 
         cat k8s/deployment.yaml
